# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triageWeb', '0002_auto_20160502_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Destroyed', 'Destroyed'), ('Unsound', 'Unsound'), ('Damaged', 'Damaged'), ('Ok', 'Ok')], default='Ok', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=50)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Reporter')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='reporter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Reporter'),
            preserve_default=False,
        ),
    ]
