# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0004_person_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 2, 21, 23, 2, 850637, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 2, 21, 23, 7, 361373, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 2, 21, 23, 11, 496265, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
