# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0005_auto_20160502_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='reporter',
            new_name='initial_reporter',
        ),
    ]
