# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0006_auto_20160502_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Reporter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='initial_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='triageWeb.Reporter'),
        ),
    ]
