# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0008_person_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='updater',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='triageWeb.Reporter'), on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Reporter'),
        ),
    ]
