# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0012_auto_20160502_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='reporter',
        ),
        migrations.AddField(
            model_name='structure',
            name='initial_reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reporter2', to='triageWeb.Reporter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='updater',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Reporter'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='structure',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=50),
        ),
    ]
