# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0013_auto_20160502_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='status',
            field=models.CharField(choices=[('destroyed', 'Destroyed'), ('unsound', 'Unsound'), ('damaged', 'Damaged'), ('ok', 'Ok')], default='ok', max_length=20),
        ),
    ]
