# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0014_auto_20160502_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('dead', 'Dead'), ('critical', 'Critical'), ('injured', 'Injured'), ('ok', 'Ok')], default='ok', max_length=20),
        ),
    ]
