# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0015_auto_20160502_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('deceased', 'Deceased'), ('critical', 'Critical'), ('injured', 'Injured'), ('ok', 'Ok')], default='ok', max_length=20),
        ),
    ]
