# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0019_auto_20160503_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageproperties',
            name='casualties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triageproperties',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triageproperties',
            name='red',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triageproperties',
            name='yellow',
            field=models.IntegerField(default=0),
        ),
    ]
