# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0024_auto_20160503_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagearea',
            old_name='tri_properties',
            new_name='properties',
        ),
    ]
