# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0025_auto_20160503_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('mapText', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('green', models.IntegerField(default=0)),
                ('yellow', models.IntegerField(default=0)),
                ('red', models.IntegerField(default=0)),
                ('casualties', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=13, default=0.0, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=13, default=0.0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center_type', models.CharField(max_length=30)),
                ('center_id', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=10)),
                ('verified', models.CharField(max_length=10)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triageWeb.CenterProperties')),
            ],
        ),
    ]
