# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0026_centerproperties_healthcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='properties',
        ),
    ]
