# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0027_remove_healthcenter_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerproperties',
            name='center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.HealthCenter'),
            preserve_default=False,
        ),
    ]
