# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0028_centerproperties_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='healthcenter',
            name='verified',
        ),
        migrations.AddField(
            model_name='centerproperties',
            name='verified',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
