# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0029_auto_20160907_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerproperties',
            name='latitude',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='centerproperties',
            name='longitude',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=50),
        ),
    ]
