# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0030_auto_20160907_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='healthcenter',
            name='longitude',
        ),
    ]
