# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0032_auto_20160907_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerproperties',
            name='center',
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='properties',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.CenterProperties'),
            preserve_default=False,
        ),
    ]
