# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0033_auto_20160907_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('deceased', 'Deceased'), ('critical', 'Critical'), ('stable', 'Stable'), ('cleared', 'Cleared')], default='cleared', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('deceased', 'Deceased'), ('critical', 'Critical'), ('injured', 'Injured'), ('ok', 'Ok')], default='ok', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='triage',
        ),
        migrations.AddField(
            model_name='person',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.HealthCenter'),
        ),
        migrations.AddField(
            model_name='condition',
            name='diseased',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Disease'),
        ),
        migrations.AddField(
            model_name='condition',
            name='injury',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Injury'),
        ),
        migrations.AddField(
            model_name='person',
            name='condition',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Condition'),
            preserve_default=False,
        ),
    ]
