# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0034_auto_20160907_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='diseased',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Disease'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='injury',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Injury'),
        ),
    ]
