# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0035_auto_20160907_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='diseased',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='injury',
        ),
        migrations.RemoveField(
            model_name='person',
            name='condition',
        ),
        migrations.AddField(
            model_name='condition',
            name='person',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Person'),
            preserve_default=False,
        ),
    ]
