# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0037_injury_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='condition',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='triageWeb.Condition'),
            preserve_default=False,
        ),
    ]
