# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0038_disease_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_type',
            field=models.CharField(choices=[('disease', 'Disease'), ('injury', 'Injury')], default='injury', max_length=20),
        ),
    ]
