# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0039_condition_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='disease_name',
            field=models.CharField(choices=[('ebola', 'Ebola')], default='ebola', max_length=20),
        ),
    ]
