# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0041_patienthistory_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_status',
            field=models.CharField(choices=[('deceased', 'Deceased'), ('critical', 'Critical'), ('injured', 'Injured'), ('ok', 'Ok'), ('deceased', 'Deceased'), ('critical', 'Critical'), ('stable', 'Stable'), ('cleared', 'Cleared')], default='ok', max_length=20),
        ),
    ]
