# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triageWeb', '0042_report_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='center_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
